# Generated by Django 4.2.20 on 2025-03-24 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_alter_company_options_company_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='parent_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_departments', to='autenticacion.department'),
        ),
    ]
