# Generated by Django 4.1.12 on 2025-03-26 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0004_alter_department_access_level'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del formulario')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('code_name', models.SlugField(max_length=100, verbose_name='Código identificador')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacion.company')),
                ('departments', models.ManyToManyField(related_name='custom_forms', to='autenticacion.department', verbose_name='Departamentos')),
            ],
            options={
                'verbose_name': 'Formulario personalizado',
                'verbose_name_plural': 'Formularios personalizados',
                'unique_together': {('company', 'code_name')},
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del campo')),
                ('field_type', models.CharField(choices=[('text', 'Texto'), ('textarea', 'Área de texto'), ('number', 'Número'), ('decimal', 'Decimal'), ('date', 'Fecha'), ('select', 'Selección'), ('checkbox', 'Casilla de verificación'), ('radio', 'Opciones')], max_length=20, verbose_name='Tipo de campo')),
                ('label', models.CharField(max_length=100, verbose_name='Etiqueta')),
                ('placeholder', models.CharField(blank=True, max_length=200, null=True, verbose_name='Texto de ayuda')),
                ('help_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto de ayuda')),
                ('required', models.BooleanField(default=True, verbose_name='Obligatorio')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('default_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Valor predeterminado')),
                ('options', models.JSONField(blank=True, null=True, verbose_name='Opciones (para select, radio)')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='dashboard.customform')),
            ],
            options={
                'verbose_name': 'Campo de formulario',
                'verbose_name_plural': 'Campos de formulario',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField(verbose_name='Datos del formulario')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacion.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='autenticacion.employee')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to='autenticacion.department')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='dashboard.customform')),
            ],
            options={
                'verbose_name': 'Datos de formulario',
                'verbose_name_plural': 'Datos de formularios',
                'ordering': ['-date_created'],
            },
        ),
    ]
