# Generated by Django 4.1.12 on 2025-04-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_formfield_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='companytheme',
            name='css_file',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Archivo CSS personalizado'),
        ),
    ]
